# Generated by Django 6.0.1 on 2026-01-12 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Utilisateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("photo_profil", models.URLField(blank=True, max_length=500)),
                ("description", models.TextField()),
                ("age", models.IntegerField()),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("lien_cv", models.URLField(blank=True, max_length=500)),
                ("telephone", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Projet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("resume", models.TextField()),
                ("image", models.URLField(max_length=500)),
                ("lien", models.URLField(max_length=500)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projets",
                        to="api.utilisateur",
                    ),
                ),
            ],
        ),
    ]
