# Generated by Django 6.0.1 on 2026-01-12 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Localisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pays", models.CharField(max_length=100)),
                ("ville", models.CharField(max_length=100)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("quartier", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="PriseDeContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_complet", models.CharField(max_length=200)),
                ("objet", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("email", models.EmailField(max_length=254)),
                ("date_envoi", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField(blank=True, null=True)),
                ("role", models.CharField(max_length=100)),
                ("nom_entreprise", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("type_de_contrat", models.CharField(max_length=50)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiences",
                        to="api.utilisateur",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReseauSocial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_plateforme", models.CharField(max_length=50)),
                ("lien", models.URLField()),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reseaux",
                        to="api.utilisateur",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("detail", models.TextField()),
                ("type_de_service", models.CharField(max_length=100)),
                ("outils", models.CharField(max_length=200)),
                (
                    "experience",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="api.experience",
                    ),
                ),
                (
                    "localisation",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.localisation",
                    ),
                ),
            ],
        ),
    ]
