# Generated by Django 6.0.1 on 2026-01-12 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_localisation_prisedecontact_experience_reseausocial_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="projet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="experiences",
                to="api.projet",
            ),
        ),
        migrations.AlterField(
            model_name="localisation",
            name="latitude",
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name="localisation",
            name="longitude",
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name="service",
            name="experience",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="api.experience",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="localisation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="services",
                to="api.localisation",
            ),
        ),
    ]
