# Generated by Django 5.2.10 on 2026-03-06 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_portfolio_config_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="experience",
            options={"ordering": ["ordre_affichage", "-date_debut", "-id"]},
        ),
        migrations.AlterModelOptions(
            name="localisation",
            options={"ordering": ["ordre_affichage", "pays", "ville"]},
        ),
        migrations.AlterModelOptions(
            name="prisedecontact",
            options={"ordering": ["-date_envoi"]},
        ),
        migrations.AlterModelOptions(
            name="projet",
            options={"ordering": ["ordre_affichage", "-id"]},
        ),
        migrations.AlterModelOptions(
            name="reseausocial",
            options={"ordering": ["ordre_affichage", "nom_plateforme"]},
        ),
        migrations.AlterModelOptions(
            name="service",
            options={"ordering": ["ordre_affichage", "nom"]},
        ),
        migrations.AlterModelOptions(
            name="utilisateur",
            options={"ordering": ["ordre_affichage", "prenom", "nom"]},
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="telephone",
            field=models.CharField(max_length=50),
        ),
    ]
