# Generated by Django 5.2.10 on 2026-03-29 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_experience_options_alter_localisation_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projet",
            name="fichier_joint",
            field=models.FileField(
                blank=True, null=True, upload_to="projets/fichiers/"
            ),
        ),
        migrations.AddField(
            model_name="projet",
            name="image_upload",
            field=models.ImageField(blank=True, null=True, upload_to="projets/images/"),
        ),
        migrations.AddField(
            model_name="projet",
            name="video_presentation",
            field=models.FileField(blank=True, null=True, upload_to="projets/videos/"),
        ),
    ]
